version: '3.7'

networks:
  mybl-net:
    driver: ${NETWORKS_DRIVER}
    external: true
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.13
    environment:
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - KIBANA_PASSWORD=${KIBANA_PASSWORD}
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./data/es:/usr/share/elasticsearch/data
    expose:
      - 9200
    ports:
      - "9200:9200"
    restart: always
    networks:
      mybl-net:
        aliases:
          - nginx_event_collector
  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.13
    links:
      - "elasticsearch"
    environment:
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=${KIBANA_PASSWORD}
    ports:
      - "5601:5601"
    restart: always
    networks:
      mybl-net:
        aliases:
          - nginx_event_collector
volumes:
  data01:
    driver: local